CHANGELOG.md, Cargo.toml, taos-error/CHANGELOG.md, taos-error/Cargo.toml, taos-macros/CHANGELOG.md, taos-macros/Cargo.toml, taos-query/Cargo.toml, taos-ws/CHANGELOG.md, taos-ws/Cargo.toml, taos-ws/src/consumer/mod.rs
* `taos-error` -> 0.2.3
* `taos-macros` -> 0.2.4
* `taos-ws` -> 0.2.2
* `taos` -> 0.2.4
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
=> chore: release

Cargo.toml, src/tmq.rs, taos-query/src/common/raw/views/lengths.rs, taos-query/src/common/raw/views/schema.rs, taos-ws-sys/src/stmt.rs, taos-ws/src/asyn.rs, taos-ws/src/stmt/mod.rs
Closes [TD-18825](https://jira.taosdata.com:18080/browse/TD-18825)
=> fix: fix websocket stmt set json tags error

Cargo.toml, taos-query/src/prelude.rs, taos-ws-sys/src/stmt.rs, taos-ws/src/asyn.rs
Closes [TD-18782](https://jira.taosdata.com:18080/browse/TD-18782)
=> fix: fix version action response error in websocket

taos-ws-py/src/lib.rs, taos-ws-sys/src/lib.rs, taos-ws-sys/src/stmt.rs, taos-ws/src/lib.rs, taos-ws/src/query/asyn.rs, taos-ws/src/query/infra.rs, taos-ws/src/query/mod.rs
Closes [TD-18952](https://jira.taosdata.com:18080/browse/TD-18952)
=> fix: sync on async websocket query support

taos-sys/src/query/raw_res.rs, taos-sys/src/tmq/raw.rs, taos-ws/src/lib.rs, taos-ws/src/query/asyn.rs, taos-ws/src/query/infra.rs, taos-ws/src/query/mod.rs
Fix [TD-18969](https://jira.taosdata.com:18080/browse/TD-18969)
=> fix: fix arm64 specific compile error

taos-ws-sys/src/lib.rs, taos-ws/src/query/asyn.rs
Close [TD-19147](https://jira.taosdata.com:18080/browse/TD-19147)
=> fix: handle error on ws disconnected abnormally

taos-ws-sys/src/lib.rs
Close [TD-19163](https://jira.taosdata.com:18080/browse/TD-19163)
=> fix(taosws): fix coredump with cmd: `taos -c test/cfg -R`

taos-ws/src/consumer/mod.rs
Close [TD-19531](https://jira.taosdata.com:18080/browse/TD-19531)
=> fix(ws): fix close on closed websocket connection

taos/src/query.rs
Fix [TD-19734](https://jira.taosdata.com:18080/browse/TD-19734)
=> fix: implicitly set protocol as ws when token param exists

taos-ws/src/consumer/mod.rs
Close [TD-20011](https://jira.taosdata.com:18080/browse/TD-20011)
=> fix: cover timeout=never feature for websocket

taos-ws/src/consumer/mod.rs
Close [TD-20057](https://jira.taosdata.com:18080/browse/TD-20057)
=> fix: remove initial poll since first msg not always none

taos-sys/src/tmq/mod.rs, taos-sys/src/tmq/raw.rs, taos-ws/src/consumer/mod.rs, taos/src/lib.rs
Close [TD-20039](https://jira.taosdata.com:18080/browse/TD-20039)
=> fix: async future not cancellable when timeout=never

taos-ws/src/query/infra.rs
Close [TD-20146](https://jira.taosdata.com:18080/browse/TD-20146)
=> fix(ws): fix error catching for query failed

taos-query/Cargo.toml, taos-query/src/util/inline_json.rs, taos-sys/src/tmq/mod.rs
Close [TD-20176](https://jira.taosdata.com:18080/browse/TD-20176)
=> fix: remove simd-json for mips64 compatibility

taos-sys/src/tmq/mod.rs
=> test: add test case for partial update block

taos-query/src/lib.rs
Close [TD-21086](https://jira.taosdata.com:18080/browse/TD-21086)
=> fix: fix r2d2 timedout error with default pool options

taos-ws/src/query/asyn.rs
Close [TD-21129](https://jira.taosdata.com:18080/browse/TD-21129)
=> fix: support api changes since 3.0.2.0

taos-optin/src/query/raw_res.rs, taos-sys/src/query/raw_res.rs
Ref: [TD-21429](https://jira.taosdata.com:18080/browse/TD-21429)
=> fix: fix memory leak when query error

taos-ws-py/src/consumer.rs, taos-ws-py/src/lib.rs, taos-ws/Cargo.toml
Close [TD-21914](https://jira.taosdata.com:18080/browse/TD-21914)
=> fix(py): fix token parsing for cloud

.github/workflows/build.yml, .github/workflows/coverage.yml, taos-optin/src/raw/mod.rs, taos-query/src/common/raw/data.rs, taos-query/src/common/raw/meta.rs, taos-query/src/util/inline_str.rs, taos-sys/src/conn/mod.rs, taos-sys/src/stmt/bind.rs, taos-sys/src/tmq/mod.rs
Closes [TD-22317](https://jira.taosdata.com:18080/browse/TD-22317)
=> fix: retry write meta when got code 0x2603

taos-query/src/common/describe.rs, taos-query/src/common/raw/rows.rs, taos-query/src/common/raw/views/mod.rs, taos-query/src/common/value.rs, taos/src/lib.rs, taos/src/query.rs
Close [TD-22686](https://jira.taosdata.com:18080/browse/TD-22686)
=> fix: impl to_string for bool type 

taos-ws/src/consumer/messages.rs, taos-ws/src/consumer/mod.rs
Ref: [TD-22806](https://jira.taosdata.com:18080/browse/TD-22806)
=> fix(ws): unimpleted type when message_type = 3

mdsn/src/lib.rs, taos-query/src/common/ty.rs, taos-query/src/lib.rs, taos/Cargo.toml
Ref: [#149](https://github.com/taosdata/taos-connector-rust/issues/149)
=> fix: fix docs building error in docs.rs

taos-sys/src/query/future.rs, taos/tests/query-error.rs
Close [TD-23408](https://jira.taosdata.com:18080/browse/TD-23408)
=> fix: fix windows ptr reading error while query failed

mdsn/src/lib.rs
Close [TD-23647](https://jira.taosdata.com:18080/browse/TD-23647)
=> fix: fix encoded username parsing error

taos-optin/src/raw/query_future.rs, taos-query/src/common/raw/data.rs, taos-sys/src/query/future.rs
Close [TD-23834](https://jira.taosdata.com:18080/browse/TD-23834)
=> fix: fix memory leak for query and tmq

taos-ws/src/consumer/mod.rs
Close [TD-23890](https://jira.taosdata.com:18080/browse/TD-23890)
=> fix(ws): fix get raw data in websocket

taos-ws-sys/cbindgen.toml
We still need to change TSDB_DATA_TYPE_MAX at least.
=> add TSDB_DATA_TYPE_GEOMETRY as the last one and change TSDB_DATA_TYPE_MAX to 21

taos-ws-sys/src/stmt.rs, taos-ws/src/consumer/messages.rs, taos-ws/src/consumer/mod.rs, taos/src/query.rs, taos/src/tmq.rs
Close [TS-3506](https://jira.taosdata.com:18080/browse/TS-3506)
=> chore: fix assignment panic via websocket

taos-ws/src/lib.rs
Close [TD-25016](https://jira.taosdata.com:18080/browse/TD-25016)
=> fix: cloud as enterprise edition

taos-query/src/common/raw/views/n_char_view.rs
=> fix(sys): fix nchar display error

rust-toolchain.toml
Close [TD-25358](https://jira.taosdata.com:18080/browse/TD-25358)
=> chore: remove nightly toolchain override

mdsn/src/lib.rs
Ref: [TD-25384](https://jira.taosdata.com:18080/browse/TD-25384)
=> fix: fix csv dsn parse error when use unix glob

.github/workflows/coverage.yml, taos-ws-sys/examples/Makefile, taos-ws-sys/examples/ws-get-err.c, taos-ws-sys/examples/ws-table-muti-bind.c
=> docs: taosws example

taos-ws-sys/src/stmt.rs
=> ci: fix Database in dropping status

taos-ws-sys/src/lib.rs, taos-ws-sys/src/stmt.rs
=> fix(ws): taosws crash while deref

taos-ws-sys/README.md, taos-ws-sys/src/lib.rs
=> fix: ws stop query crash

mdsn/src/lib.rs, taos-optin/src/lib.rs, taos-query/src/lib.rs, taos-query/src/util/mod.rs, taos-sys/src/lib.rs, taos-ws-sys/src/lib.rs, taos-ws/src/lib.rs, taos-ws/src/stmt/mod.rs, taos/examples/bind-tags.rs, taos/examples/bind.rs, taos/src/query.rs, taos/src/stmt.rs
Close [TS-3993](https://jira.taosdata.com:18080/browse/TS-3993)
=> fix: fix edtion check error for cloud

taos-ws-sys/Cargo.toml, taos-ws-sys/examples/Makefile, taos-ws-sys/examples/ws-fetch-row.c, taos-ws-sys/examples/ws-interface.c, taos-ws-sys/src/lib.rs
ws_select_db（使用 use db 实现）
ws_fetch_row（使用 fetch_block 实现）
ws_is_null（使用 fetch_block 实现）
ws_get_client_info（action: version）
=> add interface

taos-optin/src/lib.rs
Close [TS-4290](https://jira.taosdata.com:18080/browse/TS-4290)
=> fix: enterprise edition expired check error for 2.6

taos-query/src/common/raw/mod.rs, taos-query/src/common/raw/views/mod.rs, taos-query/src/common/raw/views/timestamp_view.rs, taos-query/src/common/timestamp.rs
Part of [TD-29125](https://jira.taosdata.com:18080/browse/TD-29125)
=> feat: support cast_precision for RawBlock

taos-optin/src/into_c_str.rs, taos-optin/src/raw/mod.rs, taos-optin/src/tmq/mod.rs, taos-query/src/common/raw/data.rs, taos-sys/src/conn/mod.rs, taos-sys/src/tmq/mod.rs
Close [TD-29372](https://jira.taosdata.com:18080/browse/TD-29372)
=> fix(tmq): fix coredump problems using with mimalloc

taos-query/src/common/raw/views/mod.rs
Error caused with csv batch_size=101
=> fix(common): fix unaligned error in mem::copy

taos-optin/src/types/mod.rs
=> fix(taos-optin): fix runtime memory error

Cargo.toml, taos-error/build.rs, taos-optin/src/tmq/mod.rs, taos-query/Cargo.toml, taos-query/src/common/raw/meta.rs, taos-query/src/prelude.rs, taos-query/src/tmq/mod.rs, taos-sys/Cargo.toml, taos-sys/src/lib.rs, taos-sys/src/tmq/mod.rs, taos-ws/Cargo.toml, taos-ws/src/consumer/mod.rs, taos-ws/src/query/asyn.rs, taos-ws/src/query/infra.rs, taos/src/tmq.rs, taos/tests/tmq-sync.rs
Relates to [TD-29464](https://jira.taosdata.com:18080/browse/TD-29464)
Close [TD-30437](https://jira.taosdata.com:18080/browse/TD-30437)
=> feat(tmq): support batch meta polling in tmq

taos-ws/Cargo.toml, taos-ws/src/lib.rs, taos-ws/src/query/asyn.rs, taos-ws/src/query/mod.rs, taos-ws/src/schemaless/mod.rs, taos-ws/src/stmt/mod.rs
Close [TS-4975](https://jira.taosdata.com:18080/browse/TS-4975)
=> fix(ws): use any avaliable connection behind load-balancer

taos-optin/src/tmq/raw.rs, taos-optin/src/types/tmq.rs, taos-ws/src/consumer/messages.rs, taos-ws/src/consumer/mod.rs
Close [TD-30929](https://jira.taosdata.com:18080/browse/TD-30929)
=> feat: enable msg.enable.batchmeta by default in both native/websocket

taos-ws/Cargo.toml, taos-ws/src/query/asyn.rs, taos-ws/src/schemaless/mod.rs
Modify the json parsing library to serde_json in order to support the x32 architecture
=> Modify the json parsing library to serde_json in order to support the x32 architecture

taos-query/src/lib.rs
fix: set wait and create timeouts for default pool config#ts-5192
=> fix: set wait and create timeouts for default pool config#ts-5192

.github/workflows/coverage.yml, taos-optin/src/lib.rs, taos-optin/src/raw/mod.rs, taos-query/src/lib.rs
Ref to [TD-30091](https://jira.taosdata.com:18080/browse/TD-30091)
=> enh: make native connection really asynchronous

taos-optin/src/lib.rs, taos-optin/src/raw/mod.rs, taos-ws/src/query/asyn.rs, taos/Cargo.toml, taos/examples/ts5250-builder.rs, taos/examples/ts5250.rs
Close [TS-5250](https://jira.taosdata.com:18080/browse/TS-5250)
=> fix(tmq): tmq_write_raw may stuck when network down

taos-ws/src/query/asyn.rs
fix: return raw taosError#td-31937
=> fix: return raw taosError#td-31937

taos-ws/Cargo.toml, taos-ws/src/query/asyn.rs, taos-ws/src/query/mod.rs
Fixed the ws disconnection stuck bug.
=> fix(taos-ws): fixed the ws disconnection hang bug

taos-optin/Cargo.toml, taos-optin/src/raw/mod.rs, taos-optin/src/tmq/mod.rs, taos-optin/src/tmq/raw.rs, taos-optin/src/types/tmq.rs, taos-query/src/common/field.rs, taos/src/tmq.rs
=> [TD-32792] perf(taos-optin): optimizing tmq poll

taos-optin/src/tmq/mod.rs
Modify test cases to fix `Conflict transaction not completed`
=> test(tmq): modify test cases

taos-query/src/common/raw/meta.rs
Add AlterType SetMultiTagValue
=> [TS-5690] feat(meta): add AlterType SetMultiTagValue

taos-ws-sys/cbindgen.toml
=> feat(sys): libtaosws compatible cpp

taos-ws-sys/src/lib.rs
Fix test case error on arm platform
=> test(sys): fix test case error on arm platform

mdsn/src/lib.rs
Based on https://taosdata.feishu.cn/wiki/VTSIwIV4OiSFGYky2Q4cUFw2nSg
=> feat(mdsn): allow directly special characters in dsn

mdsn/src/lib.rs
Example: `mqtt://127.0.0.1:` .
=> fix(mdsn): fix parse error in case of no-port dsn

taos-optin/src/tmq/mod.rs, taos-optin/src/tmq/raw.rs
=> fix(optin): fix tmq timeout

taos-ws/src/query/asyn.rs
fix(taos-ws): panic if deserilize text eror#TS-5892
=> fix(taos-ws): panic if deserilize text eror#TS-5892

README-CN.md, README.md
Update README.md and README-CN.md
=> [TD-33559] docs: update README

taos-query/src/de/mod.rs, taos-ws-sys/Cargo.toml, taos-ws-sys/src/lib.rs
=> fix(taos-ws-sys): fix ws_get_client_info error

taos-query/src/common/raw/data.rs, taos-query/src/lib.rs, taos-query/src/util/inline_nchar.rs
Jira: https://jira.taosdata.com:18080/browse/TD-
=> chore: fix inlinable write error

taos-ws/src/consumer/messages.rs, taos-ws/src/consumer/mod.rs
Consumer parameters support dynamic addition.
Jira: https://jira.taosdata.com:18080/browse/TS-6038
=> [TS-6038] feat(ws): consumer parameters support dynamic addition

Cargo.lock, taos-optin/src/types/mod.rs, taos-query/Cargo.toml, taos-query/src/common/decimal.rs, taos-query/src/common/itypes.rs, taos-query/src/common/mod.rs, taos-query/src/common/raw/mod.rs, taos-query/src/common/raw/rows.rs, taos-query/src/common/raw/views/decimal_view.rs, taos-query/src/common/raw/views/mod.rs, taos-query/src/common/ty.rs, taos-query/src/common/value.rs, taos-query/src/common/value/de/borrowed.rs, taos-query/src/common/value/de/mod.rs, taos-query/src/common/value/de/ref_value.rs, taos-query/src/common/value/de/value.rs, taos-query/src/helpers/describe.rs, taos-ws/src/stmt2/bind.rs
Jira: https://jira.taosdata.com:18080/browse/TS-5915
=> feat(query): support decimal types

taos-optin/src/lib.rs, taos-optin/src/raw/exec_future.rs, taos-optin/src/raw/mod.rs
=> fix(native): fix native exec_async cause coredump

taos-ws-sys/src/ws/config.rs, taos-ws-sys/src/ws/mod.rs
Jira: https://jira.taosdata.com:18080/browse/TD-
=> chore: fix config not found error

taos-ws-sys/src/ws/config.rs, taos-ws-sys/src/ws/mod.rs
Jira: https://jira.taosdata.com:18080/browse/TD-
=> chore: fix config not found error (#433)

.github/workflows/build.yml, .github/workflows/coverage.yml, rust-toolchain.toml, taos-optin/src/lib.rs, taos-optin/src/raw/mod.rs, taos-optin/src/tmq/mod.rs, taos-optin/tests/query.rs, taos-optin/tests/query_with_req_id.rs, taos-ws-sys/src/old_ws/mod.rs, taos-ws-sys/src/ws/mod.rs, taos-ws/src/consumer/mod.rs, taos-ws/src/consumer/sync.rs, taos-ws/src/query/asyn.rs, taos-ws/src/query/mod.rs, taos-ws/src/stmt/mod.rs, taos-ws/src/stmt/sync.rs, taos/examples/ts5250-builder.rs, taos/examples/ts5250.rs, taos/src/query.rs, taos/src/stmt.rs
=> chore: update toolchain channel

.github/workflows/build.yml, .github/workflows/coverage.yml, taos-ws/src/consumer/mod.rs
=> fix(ws): allow only config params with '.' in dsn

taos-ws-sys/src/old_ws/mod.rs
=> fix(sys): fix ws_get_client_info

.cargo/config.toml, Cargo.lock, taos-query/src/common/decimal.rs, taos-query/src/common/raw/mod.rs, taos-query/src/common/raw/views/decimal_view.rs, taos-query/src/common/raw/views/mod.rs, taos-query/src/common/raw/views/smallint_view.rs, taos-query/src/common/raw/views/timestamp_view.rs, taos-query/src/common/raw/views/tinyint_unsigned_view.rs, taos-query/src/common/raw/views/tinyint_view.rs, taos-ws-sys/Cargo.toml, taos-ws-sys/src/old_ws/mod.rs, taos-ws-sys/src/old_ws/tmq.rs, taos-ws-sys/src/ws/config.rs, taos-ws-sys/src/ws/mod.rs, taos-ws-sys/src/ws/query.rs, taos-ws-sys/src/ws/sml.rs, taos-ws-sys/src/ws/stmt.rs, taos-ws-sys/src/ws/stub.rs, taos-ws-sys/src/ws/tmq.rs, taos-ws-sys/src/ws/util.rs, taos-ws/src/query/asyn.rs, taos-ws/src/query/infra.rs, taos-ws/src/query/mod.rs, taos-ws/src/stmt2/mod.rs
Improve libtaosws functionality.
=> [TD-34212] enh: improve libtaosws functionality

taos-optin/src/raw/exec_future.rs
Jira: https://jira.taosdata.com:18080/browse/TD-
=> fix(optin): panic in RefCell take method

.github/workflows/build.yml
=> chore: fix build workflow

taos-ws/src/consumer/mod.rs
Fix tmq ws compatibility
Jira: https://jira.taosdata.com:18080/browse/TD-35296
=> fix(tmq): fix tmq ws compatibility

mdsn/src/lib.rs, taos-ws-sys/src/old_ws/mod.rs, taos-ws-sys/src/ws/query.rs, taos-ws/src/query/mod.rs
Support ipv6
Jira: https://jira.taosdata.com:18080/browse/TD-35112
=> feat: support ipv6

taos-query/src/common/raw/mod.rs
Add timezone method to RawBlock
Jira: https://jira.taosdata.com:18080/browse/TD-36874
=> feat: add timezone method to RawBlock

taos-ws-sys/src/ws/stmt.rs, taos-ws-sys/src/ws/stmt2.rs, taos-ws/src/consumer/conn.rs, taos-ws/src/query/mod.rs, taos-ws/src/stmt2/mod.rs
Also downgrade tracing levels in consumer cancellation.
=> enh(ws): reduce mem copy used with taos.client()
